sudo: required
language: generic
services:
  - docker
script:
  - docker-compose build
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push portenez/docker-builder:base;
    docker push portenez/docker-builder:node-n;
    docker push portenez/docker-builder:nightwatch;
    docker push portenez/docker-builder:sitespeed;
    fi
